import AppBreadcrumb from "@/components/app-breadcrumb";
import CardCount from "@/components/card-count";
import CardOptList from "@/components/card-opt-list";
import CardShipList from "@/components/card-ship-list";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <AppBreadcrumb item={[]} />
      <div className='min-h-[100vh] flex-1 rounded-xl md:min-h-min'>
        <div className='grid grid-cols-5 py-6 px-4 gap-6'>
          <div className='col-span-3 grid grid-cols-3 gap-6 self-start'>
            <CardCount />
            <CardShipList />
          </div>
          <div className='col-span-2'>
            <CardOptList />
          </div>
        </div>
      </div>
    </main>
  );
}
