import AppBreadcrumb from "@/components/app-breadcrumb";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <AppBreadcrumb item={[]} />
      <div className='flex flex-1 flex-col gap-4 p-4'>
        <div className='min-h-[100vh] flex-1 rounded-xl md:min-h-min'>
          <div className='flex items-center gap-2 px-2 py-4'>
            <h1 className='text-lg font-semibold'>Daftar Vessel</h1>
          </div>
        </div>
      </div>
    </main>
  );
}
